package com.rjcass.graph.listener;

public enum ListenerEvent
{
	MODEL_FACTORY_MODEL_CREATED,
	MANAGED_ENTITY_FACTORY_GRAPH_CREATED,
	MANAGED_ENTITY_FACTORY_NODE_CREATED,
	MANAGED_ENTITY_FACTORY_ARC_CREATED,
	MODEL_GRAPH_ADDED,
	MODEL_GRAPH_REMOVED,
	MODEL_GRAPHS_MERGED,
	MODEL_GRAPHS_SPLIT,
	GRAPH_MODEL_SET,
	GRAPH_NODE_ADDED,
	GRAPH_NODE_REMOVED,
	GRAPH_REMOVED,
	NODE_GRAPH_SET,
	NODE_ARC_ADDED,
	NODE_ARC_REMOVED,
	NODE_REMOVED,
	ARC_START_NODE_SET,
	ARC_END_NODE_SET,
	ARC_DIRECTED_SET,
	ARC_REVERSED,
	ARC_REMOVED
}
